### ISSUE TITLE
Issue while when complining

### ISSUE THREAD

**Issue by shidhu40** [ZhiyueYi/demo-in-blog#1]
I have copied same breadcrumb code  structure and facing following issues:

 src/app/breadcrumb/breadcrumb.component.ts:23:7 - error TS2345: Argument of
e 'MonoTypeOperatorFunction<Event>' is not assignable to parameter of type 'O
atorFunction<Event, Event>'.
   Types of parameters 'source' and 'source' are incompatible.
     Type 'import("C:/xampp/htdocs/angular-rest-api/node_modules/rxjs/interna
bservable").Observable<import("C:/xampp/htdocs/angular-rest-api/node_modules/
gular/router/router").Event>' is not assignable to type 'import("C:/xampp/htd
/angular-rest-api/node_modules/rxjs/internal/Observable").Observable<Event>'.

       Type 'import("C:/xampp/htdocs/angular-rest-api/node_modules/@angular/r
er/router").Event' is not assignable to type 'Event'.
         Type 'ActivationEnd' is missing the following properties from type '
nt': bubbles, cancelBubble, cancelable, composed, and 18 more.

 23       filter((event: Event) => event instanceof NavigationEnd),
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ZhiyueYi** [comment]
Hi @shidhu40 , when I wrote this component 2 years ago, I was using rxjs with version 5.5.6. Now rxjs has released the 7th version beta, so I guess there are some breaking changes in their data structures.

**Comment by esfomeado** [comment]
@shidhu40 

`      filter(event => event instanceof NavigationEnd),
`
